### ISSUE TITLE
Titres et tabs en mode paysage

### ISSUE THREAD

**Issue by Orabig** [Orabig/Judgehype#1]
(From Lona)
Pour la version en mode paysage (bon point, j'ai même pas testé car j'utilise quasiment jamais mon téléphone en mode paysage), j'imagine que tu es allé au plus simple, mais ça serait mieux d'avoir le même système de tabs qu'en mode portrait. Déjà pour l'homogénéité dans l'application, mais aussi parce que le menu ne s'affiche pas entièrement
![bug1](https://cloud.githubusercontent.com/assets/2180151/10882138/947b3634-8168-11e5-8872-41914822c446.png)

**Comment by Orabig** [comment]
Il faut que je vois si c'est possible.
J'utilise le traitement standard de Google pour son ActionBar, et ils ont décidé (j'imagine) que si on utilise le mode paysage, alors on a moins de place en vertical, et donc il faut utiliser ce menu (moche) plutôt que les tabs.
Je me souviens avoir cherché un peu, sans trouver comment supprimer ce comportement par défaut.

Mais c'est moche, j'en suis conscient. Je vais le noter en enhancement à faire plus tard..

**Comment by AllInOneMighty** [comment]
C'est un bon point note, d'utiliser moins de place verticalement.

Sinon l'autre solution c'est de faire en sorte que quand le menu s'affiche, il affiche autre chose? Un rectangle avec toutes les options affichées?

Quelque chose comme:

---

| Diablo | StarCraft    |
| WoW   | Overwatch |
...

---
