### ISSUE TITLE
Quels effets sonores ??

### ISSUE THREAD

**Issue by Orabig** [Orabig/Judgehype#12]
(From Lona)
"Désactiver les effets sonores" --> Ça veut dire quoi exactement? Je n'ai pas l'option cochée et l'application est complètement muette (à part YouTube et Twitch bien sûr).

**Comment by Orabig** [comment]
Haha, effectivement, je me doutais qu'on poserait la question.
Actuellement, l'application fait très peu de bruit (surtout depuis qu'on a supprimé le video-splash), mais on a un bruit de cartes quand on affiche des cartes hearthstone.
Par ailleurs, Je ne l'ai pas encore implémenté, mais je me demandais si je devais ajouter des effets sonores discrets sur le changement de pages (swipe horizontal), le click sur un article, etc....

**Comment by AllInOneMighty** [comment]
Bonne question. Je pense que c'est assez compliqué de choisir les bons sons, et l'autre question est: est-ce que c'est vraiment nécessaire? C'est fun, mais est-ce que ça ajoute à l'application?

**Comment by Orabig** [comment]
Tu es en train de sous-entendre que le fun n'apporte rien à une application ?

**Comment by AllInOneMighty** [comment]
Nan, je sous-entends que c'est pas forcément fun. (Okay j'ai dit que ça l'était mais c'était plus une figure de style.)

C'est un peu comme sur Windows: t'as pas envie que toutes tes fenetres et raccourcis fassent un bruit quand tu les touches ;P
