### ISSUE TITLE
Style différent pour le bouton "Afficher les commentaires"

### ISSUE THREAD

**Issue by AllInOneMighty** [Orabig/Judgehype#16]
Le bouton 'Afficher les commentaires' est un peu bulky... il rend pas terrible. Bon, c'est que du design, mais si tu as une idée pour le rendre plus "beau", ça serait top! Genre un bouton en relief, par exemple?
https://www.google.com/design/spec/components/buttons.html
![image](https://cloud.githubusercontent.com/assets/1002605/10891912/793b29fa-8155-11e5-9090-d5e72e939d03.png)

**Comment by Orabig** [comment]
Fixed

Ca donne ça maintenant :

![comment](https://cloud.githubusercontent.com/assets/2180151/11019713/a8fa63a4-8605-11e5-84fb-76414fad25d5.png)
