### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by AllInOneMighty** [Orabig/Judgehype#17]
Je sais pas si c'est prévu d'avoir une fonction recherche dans l'app (si c'est pas le cas, tu peux fermer ce bug), mais si c'est le cas... cette page est juste un tracker de feature request :)

**Comment by Orabig** [comment]
Je le note en enhancement... Mais clairement, ca ne dépend pas de moi...

J'aurai besoin de l'API correspondante. Donc... "When it's done..."
