### ISSUE TITLE
Affichage des liens IMGUR

### ISSUE THREAD

**Issue by Orabig** [Orabig/Judgehype#2]
(From Lona)
Si je vais sur cette news avec l'application: http://overwatch.judgehype.com/news/la-killer-feature-d-overwatch-est-connue-c-est-la-corde-a-sauter-144463/
Voici ce que j'obtiens (le deuxième screenshot, c'est quand je clique sur le lien):
![bug2](https://cloud.githubusercontent.com/assets/2180151/10881855/9deb51f6-8166-11e5-8489-2e8d04156f4e.png)

![bug3](https://cloud.githubusercontent.com/assets/2180151/10881858/a114db7c-8166-11e5-82cc-9c6cca218d3f.png)

Probablement un problème de lien/intent.

**Comment by Orabig** [comment]
Oui, c'est parce que les iframes générés par imgur pour insérer leurs images animées ne sont pas compatibles avec les téléphones (Android du moins)....
J'ai aussi vu ça ce week-end, et je ne pense pas pouvoir faire grand chose.
Malheureusement, je ne pourrai jamais être compatible à 100% avec tout ce que pourront mettre les rédacteurs dans les articles, puisqu'ils peuvent mettre n'importe quel code HTML.

Essaye de regarde la page sur un "vieux" navigateur, et ca plantera tout aussi bien.

Je pourrai le corriger, mais sachant qu'on doit avoir en moyenne un imgur tous les 12 ans sur le site (j'ai fait le calcul), je pense que le jeu n'en vaut pas la chandelle. Les curieux ouvriront leur navigateur.

(j'étais déjà très heureusement surpris de voir que le code pour les sondages fonctionnait pratiquement parfaitement. C'etait pas gagné)

**Comment by AllInOneMighty** [comment]
> Malheureusement, je ne pourrai jamais être compatible à 100% avec tout ce que pourront mettre les rédacteurs dans les articles, puisqu'ils peuvent mettre n'importe quel code HTML.

Je pense qu'il est là le problème :P

**Comment by Orabig** [comment]
Je ne me prononcerais pas sur le sujet...
Et puis l'ordre c'est chiant. (c'est bon pour les paladins)
J'ai toujours trouvé le chaos bien plus intéressant....
