### ISSUE TITLE
Problème de padding dans l'entête des commentaires

### ISSUE THREAD

**Issue by HinShell** [Orabig/Judgehype#25]
Sur ma tablette, si la taille de la police est à => Grand, j'ai des problèmes de padding dans l'entête des commentaires.
Pas méchant mais ugly 
![screenshot_2015-11-03-21-16-14](https://cloud.githubusercontent.com/assets/15639171/10920680/c72b4010-8271-11e5-9365-ff0177211dc3.png)

**Comment by Orabig** [comment]
Merci, bien noté.
L'application n'est pas vraiment prévue pour les tablettes. Je pense améliorer cette compatibilité dans la version 1.3
