### ISSUE TITLE
Problème d'affichage des "sticky topic"

### ISSUE THREAD

**Issue by HinShell** [Orabig/Judgehype#26]
Au démarrage de l'application le sticky topic s'affiche correctement en haut de la liste des articles dans la tab "À la une". Si je refresh il disparaît de la tab et s'affiche en double dans la tab suivante.
![screenshot_2015-11-03-21-43-10](https://cloud.githubusercontent.com/assets/15639171/10921222/88672e68-8274-11e5-84ce-fcab53aeca70.png)

**Comment by HinShell** [comment]
Peut-être un rapport avec le #23 ?

**Comment by Orabig** [comment]
certainement
