### ISSUE TITLE
Nombre d'article limité dans la liste principale

### ISSUE THREAD

**Issue by Orabig** [Orabig/Judgehype#3]
(From Lona)
Y'a pas moyen d'aller plus loin qu'un certain nombre de news sur chaque onglet (genre 15-20), c'est normal? J'imagine que c'est par design mais je voudrais confirmer ;-)

**Comment by Orabig** [comment]
C'est effectivement un point que j'ai laissé de coté pour le moment. Je voulais être certain que tout fonctionne bien avec une liste statique (limitée à 15 articles) avant de tenter l'implémentation d'une liste qui s'agrandit dynamiquement quand on scrolle vers le bas (chose que j'ai implémenté dans la vue d'un article, quand on swipe horizontalement)

Dans l'idéal, j'aurai d'ailleurs besoin d'une nouvelle API qu'il faudra demander à Sharas, mais je n'ai pas encore osé lui demander, il avait l'air bien booké :)

**Comment by AllInOneMighty** [comment]
Sharas est toujours bien booké, mais c'est pas vraiment vrai. :P
