### ISSUE TITLE
Problème de caractère

### ISSUE THREAD

**Issue by Orabig** [Orabig/Judgehype#4]
(From Lona)
Un petit problème de caractère sur cette news: http://hearthstone.judgehype.com/news/hwc-presentation-et-planning-complet-de-l-evenement-144448/
![bug4](https://cloud.githubusercontent.com/assets/2180151/10881892/e196fc20-8166-11e5-902a-d54f158d583d.png)

**Comment by Orabig** [comment]
Ca arrive parfois, pratiquement toujours à cause du caractère '
Selon les sources, logiciels utilisés, systèmes .... ce caractère est parfois remplacé par ` ou ’ ou encore ’ (oui, ces 4 caractères sont tous différents !)
Je vois que cet article a été rédigé par ZhemV. Je ne sais pas de quel caractère il s'agit (et surtout quel code Unicode)
Je le note et corrige dès que possible. Je vais bien finir par tous les attraper (non, pas les pokemons)

**Comment by Orabig** [comment]
Corrigé. Il s'agissait du caractère Unicode 2019  RIGHT SINGLE QUOTATION MARK
(il fallait le trouver celui-là...)

**Comment by Orabig** [comment]
Pour information et mémoire, je traite actuellement les caractères suivants : 
'PRIVATE USE TWO'  (U+0092)
'MODIFIER LETTER APOSTROPHE' (U+02BC)
'RIGHT SINGLE QUOTATION MARK'  (U+2019)
Ils sont tous remplacés par un 
'APOSTROPHE' (U+0027)
qui est plus moche, mais a l'avantage d'être reconnu même sur les téléphones de 1975....

**Comment by AllInOneMighty** [comment]
Bah tu peux rouvrir le bug alors :D

**Comment by Orabig** [comment]
Pourquoi ? Tu as rencontré d'autres problèmes, ou parce que l'apostrophe est un peu rustique ?

**Comment by AllInOneMighty** [comment]
Ha non en fait j'ai mal compris: j'ai cru que tu étais en train de traiter les caractères ci-dessus, alors qu'en fait tu disais que l'app gérait ces caractères. Autant/temps pour moi!

**Comment by Orabig** [comment]
"Au temps..." ;)

**Comment by AllInOneMighty** [comment]
Ha non on va pas commencer! :P
