### ISSUE TITLE
Look bouton FAB "ajout commentaire"

### ISSUE THREAD

**Issue by Orabig** [Orabig/Judgehype#7]
(From Lona)
Le bouton de commentaire est vachement mieux et peut rester tel quel pour la release je pense, mais quelque chose me chagrinait... et effectivement il est un peu trop bas par rapport au standard. Rien de grave, cependant. L'ombre n'est pas assez forte, 
![bug6](https://cloud.githubusercontent.com/assets/2180151/10881958/4cb8c966-8167-11e5-8828-13fc863c7998.png)

Pour référence, le bouton sur une autre application :
![bug7](https://cloud.githubusercontent.com/assets/2180151/10881968/62426440-8167-11e5-828e-a484be9980c9.png)

**Comment by Orabig** [comment]
On est dans le cosmétique fin, là...
Il faut être pointu pour le voir.

Et si seulement Google fournissait des API de support permettant de faire ça facilement..... :p

**Comment by AllInOneMighty** [comment]
Tout est écrit ici cependant: https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

_The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop._

**Comment by Orabig** [comment]
Le problème n'est pas de savoir ce qu'il faut faire, mais comment l'implémenter :)
Un même code donne des résultats totalement différents selon sur quelle version d'android on se trouve. Tu te souviens quand le bouton touchait le bord chez toi ? Il était positionné correctement de mon coté :)

**Comment by Orabig** [comment]
C'est corrigé.
Voici ce que ca donne dans les émulateurs :

Samsung Galaxy (API 19)

![fab-galaxy-api19](https://cloud.githubusercontent.com/assets/2180151/10969227/39f7dc06-83c7-11e5-8420-bff2ece92fba.png)

Nexus 5 (API 23)

![fab-nexus5](https://cloud.githubusercontent.com/assets/2180151/10969233/42c8258e-83c7-11e5-9913-3cee6c8f2889.png)

Nexus 6 (API 22)

![fab-nexus6](https://cloud.githubusercontent.com/assets/2180151/10969237/463bac2c-83c7-11e5-86c9-70733b66079b.png)

**Comment by AllInOneMighty** [comment]
Humm je pense que l'ombre n'est pas assez prononcée... :¦
